.\" See section COPYING for conditions for redistribution
.\"
.TH dune4kids 1 2006-12-10 "white_dune 0.99rc141"
.SH NAME
dune4kids \- beginner GUI for vrml97/x3d editor
.SH SYNOPSIS
.br
.B dune4kids
[
.I options
]
[
.I file.wrl
.I file.x3dv
.I file.x3d
.IR "\.\.\."
] 
.P
.IR "\.\.\."
.SH DESCRIPTION
.B dune4kids
/ dune4kids is a beginners GUI for white_dune
.br
white_dune is a graphical editor for the Virtual Reality Modeling Language 
(VRML97), ISO/IEC 14772-1:1997.
.br
See in the white_dune manpage for details
.SH "SEE ALSO"
dune(1),


