.\" See file COPYING for conditions for redistribution.
.
.TH dune4kids 1 2019-01-02 "white_dune 0.99pl1248"
.SH NAME
dune4kids \- simplified VRML97/X3D editor GUI
.SH SYNOPSIS
.B dune4kids
.RI "[ " options " ]"
[
.IR file.wrl " | " file.x3dv " | " file.x3d " [ " "\.\.\." " ]"
] 
.
.SH DESCRIPTION
.PP
.B dune4kids
is a simplified GUI for white_dune,
a graphical editor for the Virtual Reality Modeling Language.
.
.PP
See the white_dune ("\fBdune\fR") manpage for details.
.
.SH "CONFORMING TO"
.pp
Virtual Reality Modeling Language (VRML97),
ISO/IEC 14772-1:1997.
.  
.SH "SEE ALSO"
.BR dune (1).

