#!/bin/sh

# This file is free software; the Free Software Foundation    
# gives unlimited permission to copy, distribute and modify it.

export DUNE_BINARY=efencedune
make ../bin/efencedune
`dirname $0`/gdbstart $*
