#!/bin/sh
set -e
#if [ "$1" = "configure" ]; then
#	if [ -d /usr/doc -a ! -e /usr/doc/dune -a -d /usr/share/doc/dune ]; then
#		ln -sf ../share/doc/dune /usr/doc/dune
#	fi
#fi
if test -x /usr/bin/update-menus; then 
   update-menus
fi
