/* XPM */
static char * aaa87o_7a[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 7 1 0 0",
/* colors */
" 	s iconColor2	m white	c white",
".	s none	m none	c none",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconColor1	m black	c black",
"O	s iconGray7	m black	c #424242424242",
"+	s iconColor5	m black	c blue",
"@	s iconColor4	m white	c green",
/* pixels */
"                         .......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXooXoOOXXOOXOOXooXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXXooXXooOoOOXooXOooXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXooXoOOXoOXoXooOooXXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXoooXooOXXoOOooXooOOXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" XXoOOXOooXoOOoXXOOXoXXXo.......",
" XXXXXXXXXXXXXXXXXXXXXXXo.......",
" ++++OooOoXOooXooOOoooXXo.......",
" ++++++XXXXXXXXXXXXXXXXXo.......",
" @@+o@+++OOooXOOOOXooXXXo.......",
" @@@@@@++XXXXXXXXXXXXXXXo.......",
" @@@@@@@+XXXXXXXXXXXXXXXo.......",
" ++@@@@@++oooXoXXOXOoXXXo.......",
" +++@@@@@++XXXXXXXXXXXXXo.......",
" +++++O@@++XoooXXOOOoXXXo.......",
" ++++++@@+++XXXXXXXXXXXXo.......",
" ++O+O+oO+@+OXoOOoXoXXXXo.......",
" ++@@@+@@@@+XXXXXXXXXXXXo.......",
" +++@@+o@oo+XXXXXXXXXXXXo.......",
" +++@@+@@+@+XXXXXXXXXXXXo.......",
" +++@++@++++XXXXXXXXXXXXo.......",
" ++++++++@++XXXXXXXXXXXXo.......",
" oooooooooooooooooooooooo......."};