/* XPM */
static char * aaaGzaqbn[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 14 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor6	m white	c yellow",
"X	s iconGray4	m white	c #949494949494",
"o	c #999999999999",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray5	m black	c #737373737373",
"@	s iconGray2	m white	c #bdbdbdbdbdbd",
"#	s iconGray1	m white	c #dededededede",
"$	c #CCCCCCCCCCCC",
"%	s iconGray3	m white	c #adadadadadad",
"&	s iconGray8	m black	c #212121212121",
"*	s iconGray7	m black	c #424242424242",
"=	s iconColor3	m black	c red",
"-	s iconColor4	m white	c green",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                  .                             ",
"                 .X                             ",
"                .X.X                            ",
"               .X.X.X                           ",
"              .X.X.X..                          ",
"             .X.X.X.XoO                         ",
"            .X.X.+.X.+.O                        ",
"           .+.+.+.X.X+OOO                       ",
"     o@@#+.+.+.X.X.+.oO.O                       ",
"  o@$$##X.+.+.+.X.X.X.XO.O                      ",
"X%%$$+#+.+.X.X.+.X.X.X.OOO.                     ",
"X%@$+#+.+.+.+.+.X.X.X.XOO.OO     &&&&&          ",
"OX%+#+.+.+.+.X.X.X.X.X.XOOO.oX  &&&**&          ",
"O#+#+.+.+.+.+.X.X.+.X.X..OOO.o%o&**OO*&         ",
"#+#+.+.+.+.+.+.X.X.X.X.XOO.OOOo%&*@+%@*         ",
"##+.+.+.+.+.+.+.+.+.X.X.+.OOO.XX&X*@@**+X       ",
"#+.+.+.+.+.+.+.+.+.X.X.X.OO.OOOX&+&%@&*X+=+XX   ",
"+.+.+.+.+.+.+.+.+.X.X.X.X+OO.OO&*.=.=.*X=&++++++",
".+.+.+.+.+.+.+.+.+.+.X.X.+.OOO.&**.=..*X===XXXXX",
"+.+.+.+.+.+.+.+.+.+.+.+.+.OOO.OX+--.----===XX+XX",
".+.+.+.+.+.+.+.X.+.+.+.+.++.OOO&&**@@*&&==%ooX++",
"+.+.+.+.+.+.+.+.X.+.+.+.%.o+.OO&&*%@@%*&==%oooXX",
".+.+.+.+.+.+.+.+.+.+.X.X++&&&&&&**%@@%*&&&++XoX+",
"+.+.+.+.+.+.O.+.+.+.+.X&&&&&&&&&*%@@@@%&&&&&&++O",
".+.+.+.+.+.+.+.+.+.+.+&&.+.X+&&&&@@@@@@*&&X&&&++",
"+.+.+.+.+.+.+.+.+.+.+O&.X.X.&&&&&@$$$$$@*&+XX&&+",
".+.+.+.+.+.+.+.+.+.+.O.X.X.+&&&&*@$$$$$@*&XooX&X",
"*.+.+.+.+.+.+.+.+.+.+.+.X.+.&&&&@@$$$$$@*&XXoXo%",
"+***X+%+.+.+.+.O.+.+.+.+.+.X&&&*@@$$$$$@*&&X%%oo",
"++X+++++X+X%+%+.+.+.+.+.+.+.&&&*@$$$$$$$@&&X%o%%",
"+++X+++++XX+X+%X%X%%%X.o.+.+&&&*@$$$$$$$@&&%oooX",
"XXX+XXX+X+XXXX+XXXXXX%%%X%X%&&&&@$$$$$$$@&&%%%@%",
"X+XXXXXXXXXXX+X+XXXXXXoXXX%X%&&&@@@@@@@@&&&%%%%o",
"oXXXXXXoXXXoXXXXXXXXXXXXX%XoX&&&%ooXoXo%&*@%@%@@",
"+XX+XXXXXXXoXXXXXXXXooXooooXXX&O*+++++&**o@%@%%%",
"XXoXXoXXoXoXXoXXXoXooXXoX%X%%%oo&&&o&&&%%%%@o$%@",
"XXoXXXXXXoXXX%XXX%X%o%XXoo%%%o.=.=.%.=.=.@%%%%%%",
"XXXXXXXXXXXXo%X%oXoXo%oo%%X%%%oOOX+@&+XoO@@%%%@@",
"oXXoo%XXXoXXXXX%XooXoXo%oo%o%o%%%%o%%%%%%%@%%%@o"};