/* XPM */
static char * aaa2Kay_m[] = {
/* width height ncolors cpp [x_hot y_hot] */
"36 36 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor6	m white	c yellow",
"X	s iconGray4	m white	c #949494949494",
"o	s iconGray8	m black	c #212121212121",
"O	s iconGray6	m black	c #636363636363",
"+	s iconGray3	m white	c #adadadadadad",
"@	c #CCCCCCCCCCCC",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray2	m white	c #bdbdbdbdbdbd",
"%	s iconGray7	m black	c #424242424242",
"&	c #999999999999",
"*	s iconGray5	m black	c #737373737373",
"=	s iconColor1	m black	c black",
"-	s iconColor3	m black	c red",
";	s iconColor5	m black	c blue",
":	s iconColor4	m white	c green",
/* pixels */
"                                    ",
"                                    ",
"                                    ",
"                                    ",
"                                    ",
"                                    ",
"               .                    ",
"              .Xo                   ",
"             .X.X.                  ",
"            .X.X.OO                 ",
"           .X.X.XOO                 ",
"          .X.X.X.X.O                ",
"   +@@X#X.X.X.X.X.OOO               ",
"OX+$$X#X.%.%.X.X.X%.O               ",
"OO&++#X.X.X.X.X.X.XO.O*   ooo       ",
"OO+X+X.X.X.X.X.X.X.%OO=&X=%%%o      ",
"O+++O.O.X.X.X.X.X.X%%.OXXo+o$%   -  ",
"O++O.O.O.X.X.X.X.X.XOOO=Xo;o;&**-   ",
"O+O.O.O.X.X.X.%.X.X.%OOO=:.-.::---**",
"OO.O.O.O.O.X.X.X.X.X%%.O=oo.X%=o-*XX",
"O.O.O.O.O.O.X.X.%.X.X%OO==%+&o=oX-**",
"OO.O.O.O.O.O.X.X.X.X.%%.=o%++%=oXX&X",
"O.O.O.O.O.O.O.%.%.X======o&+$+o====*",
"OO.o.O.O.O.O.O.X.X===X%===+$$+==*===",
"O.O.O.O.O.O.O.O.X.X.X.===o$@@$$=**XX",
"Oo.o.o.O.O.O.O.O.O.X.X===$$@@@$==XXX",
"OoooooO.O.O.O.O.O.O.X.==o$$@@@$o=&&&",
"O*O*O********O.O.O.O.O==o$$@@@$o=&XX",
"OOX*******X**X**XXX*O.==o$$@@@$o=X+&",
"O*****X***X**XX**XX*X*==o+$$$$+==++&",
"O*XXX*XXXXX*X*XX*&XXX&X==&XXXXX=+X&+",
"O**X*XXX*XXXX**XXXX*XX&XX%=O$%%&&+&+",
"O*XXXX*XXXX*X**X&X&&+&X&&O-&&-X+&++$",
"OX&**XX**&&XXXXXX*X+&X&&.-.oo.-.++++",
"OXX&XX*X*XXXX&XX&&&X&+X&&&X&X&+++&++",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"};