# This Makefile is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.

DISTFILES= \
	groupbox.c \
	header.c \
	resload.c \
	statusbar.c \
	toolbar.c \
	tree.c \
	util.c \
	Makefile

dname:
		mkdir ../../`cat ../../.dname`/swt/generic
		ln $(DISTFILES) ../../`cat ../../.dname`/swt/generic
