

















/*
 * swlanguages.h.m4 
 *
 * swlanguages.h is autogenerated from swlanguages.h.m4
 *
 * Copyright (C) 2006 J. "MUFTI" Scheurich
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program (see the file "COPYING" for details); if 
 * not, write to the Free Software Foundation, Inc., 675 Mass Ave, 
 * Cambridge, MA 02139, USA.
 */
























































enum duneLanguages {
    SW_LANG_english = 0
,
    SW_LANG_portuguese = 1 
,
    SW_LANG_german = 2 
,
    SW_LANG_italian = 3 
,
    SW_LANG_french = 4 
   

,
    SW_LANG_PT = 1 
,
    SW_LANG_DE = 2 
,
    SW_LANG_IT = 3 
,
    SW_LANG_FR = 4 
   
};






#ifndef swLangYes
# define swLangYes(x) (x == SW_LANG_portuguese) ? "sim" : (x == SW_LANG_german) ? "Ja" : (x == SW_LANG_italian) ? "si" : (x == SW_LANG_french) ? "oui" :   "yes"
#endif
#ifndef swLangNo
# define swLangNo(x) (x == SW_LANG_portuguese) ? "nao" : (x == SW_LANG_german) ? "Nein" : (x == SW_LANG_italian) ? "no" : (x == SW_LANG_french) ? "non" :   "no"
#endif

