# This Makefile is free software; the Free Software Foundation
# gives unlimited permission to copy, distribute and modify it.

DISTFILES = swt.c dragdrop.cpp browser.c swt_private.h Makefile \
	    swt.dsp

target:
		@echo "you didn't *really* expect that to work, did you?"

dname:
		mkdir ../../`cat ../../.dname`/swt/win32
		ln $(DISTFILES) ../../`cat ../../.dname`/swt/win32
