#ifndef WIN32
#include "unistd.h"
#endif

#line 2 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[271] =
    {   0,
        0,    0,   53,   44,   49,   50,   49,   51,   48,   51,
       51,   51,    7,    7,   45,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,    3,
        4,   44,   44,   44,   44,    1,    2,   48,   44,   44,
       45,   49,   50,   47,    0,   46,    0,   48,    0,    7,
        7,    5,    5,    0,    0,   16,   44,   44,   44,   44,
       44,   44,   20,   44,   44,   44,   44,   44,   44,   44,
       24,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       48,   48,   44,   47,    0,    5,    0,    6,    8,   44,
       44,   17,   44,   44,   44,   44,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   26,   44,   44,   44,   44,
       44,   44,   44,   48,   48,   43,    0,    5,   44,   44,
       44,   44,   44,   44,   37,   21,   44,   44,   44,   44,
       44,   44,   25,   38,   44,   44,   44,   44,   44,   44,
       44,   48,   48,   44,   44,   44,   44,   19,   44,   44,
       22,   44,   23,   44,   44,   44,   44,   44,   30,   44,
       44,   44,   48,   48,   44,   44,   14,   44,   15,   44,
       44,    9,   44,   44,   44,   44,   44,   44,   44,   44,
       48,   48,   44,   44,   44,   35,   44,   44,   10,   27,
       44,   44,   44,   44,   44,   44,   48,   48,   44,   44,

       44,   44,   44,   28,   44,   44,   44,   44,   44,   48,
       48,   36,   44,   44,   44,   44,   44,   44,   31,   44,
       44,   48,   48,   48,   48,   48,   44,   44,   44,   44,
       44,   44,   44,   32,   42,   48,   48,   48,   44,   18,
       44,   44,   44,   44,   33,   42,   48,   48,   48,   44,
       44,   44,   29,   44,   48,   48,   48,   44,   44,   12,
       44,   41,   48,   48,   11,   13,   34,   39,   40,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    1,    1,    8,    1,
        1,    1,    9,    2,   10,   11,    1,   12,   13,   14,
       15,   16,   16,   16,   16,   17,   16,   18,    1,    1,
        1,    1,    1,    1,   19,   20,   21,   22,   23,   24,
        1,    1,   25,    1,    1,   26,   27,   28,   29,   30,
        1,   31,   32,   33,   34,   35,    1,   36,    1,    1,
       37,   38,   39,    1,    1,    1,   40,   20,   41,   42,

       43,   44,   45,   46,   47,    1,   48,   49,   50,   51,
       52,   53,    1,   54,   55,   56,   57,   58,    1,   59,
       60,   61,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   64,    1,    1,    1,
       65,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   66,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    2,    3,    3,    2,    2,    2,    2,    1,    1,
        4,    5,    5,    5,    5,    5,    5,    1,    6,    6,
        6,    6,    5,    6,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    6,
        6,    6,    5,    6,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    7,    1,
        1,    2,    2,    1,    1,    1
    } ;

static const flex_int16_t yy_base[279] =
    {   0,
        0,   60,  634,  615,   66,   65,   71,   68,    0,  635,
       66,   72,   79,   80,    0,   80,   81,   82,   83,   89,
       86,   91,   93,   97,  102,   98,  103,  117,   99,  635,
      635,  106,  107,  111,  112,  635,  635,  105,  118,  614,
        0,  146,  635,    0,  136,  635,    0,    0,  143,  150,
      164,  182,  198,  214,    0,  613,  125,  150,  148,  153,
      166,  171,  612,  152,  190,  173,  149,  129,  185,  200,
      611,  170,  217,  199,  188,  201,  202,  214,  215,  216,
      597,  612,  218,    0,  236,  261,  273,  279,    0,  229,
      245,  608,  225,  238,  247,  240,  248,  279,  282,  253,

      281,  262,  284,  285,  289,  607,  263,  219,  264,  292,
      293,  295,  300,  597,  601,  604,  315,  321,  321,  299,
      324,  325,  301,  326,  603,  602,  322,  330,  305,  302,
      328,  336,  601,  600,  340,  342,  344,  345,  346,  347,
      348,  591,  611,  349,  351,  350,  352,  597,  353,  356,
      596,  355,  595,  354,  357,  358,  360,  366,  590,  372,
      373,  370,  594,  558,  374,  376,  574,  377,  573,  378,
      386,  570,  390,  395,  396,  398,  399,  400,  403,  404,
      546,  553,  406,  410,  405,  549,  414,  407,  548,  545,
      409,  413,  412,  417,  420,  421,  549,  550,  424,  426,

      435,  430,  422,  542,  428,  425,  427,  432,  445,  548,
      465,  540,  449,  450,  451,  453,  466,  470,  538,  455,
      471,  543,  497,  548,  545,  485,  474,  475,  478,  473,
      481,  482,  485,  531,    0,  492,  489,  488,  487,  525,
      490,  488,  492,  489,  521,    0,  494,  481,  480,  499,
      501,  497,  517,  502,  516,  482,  481,  498,  503,  506,
      504,    0,  506,  304,  246,  242,  128,    0,    0,  635,
      564,  571,  578,  582,  589,  596,  599,  605
    } ;

static const flex_int16_t yy_def[279] =
    {   0,
      270,    1,  270,  271,  270,  270,  270,  272,  273,  270,
      270,  270,  274,  270,  275,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  270,
      270,  271,  271,  271,  271,  270,  270,  273,  271,  271,
      275,  270,  270,  276,  272,  270,  272,  273,  270,  274,
      270,  270,  270,  270,  277,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      273,  273,  271,  276,  270,  270,  270,  270,  277,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  273,  273,  271,  270,  270,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  273,  273,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  273,  273,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      273,  273,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  273,  273,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  273,
      273,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  273,  273,  273,  273,  273,  271,  271,  271,  271,
      271,  271,  271,  271,  278,  273,  273,  273,  271,  271,
      271,  271,  271,  271,  271,  278,  273,  273,  273,  271,
      271,  271,  271,  271,  273,  273,  273,  271,  271,  271,
      271,  273,  273,  273,  271,  271,  271,  273,  273,    0,
      270,  270,  270,  270,  270,  270,  270,  270
    } ;

static const flex_int16_t yy_nxt[702] =
    {   0,
        4,    5,    6,    7,    5,    8,    9,   10,   11,   11,
       12,   13,   14,   14,   14,   14,   14,   15,   16,    4,
       17,   18,   19,   20,   21,    4,   22,   23,    4,   24,
       25,   26,   27,   28,   29,    4,   30,   10,   31,    4,
        4,    4,   32,   33,    4,    4,   34,    4,    4,    4,
        4,   35,    4,    4,    4,    4,    4,    4,    4,    4,
        4,   36,   37,    4,    4,    4,   38,   42,   43,   42,
       42,   44,   42,   46,   42,   42,   49,   50,   51,   51,
       51,   51,   51,   52,   52,   52,   52,   52,   52,   53,
       53,   51,   51,   51,   51,   51,   51,   41,   41,   41,

       41,   54,   54,   41,   59,   47,   41,   61,   41,   57,
       41,   56,   62,   64,   41,   41,   41,   63,   60,   41,
       41,   54,   54,   41,   41,   39,   65,   66,   41,   41,
       68,   71,   58,   72,   41,   41,   67,   55,   69,   81,
       82,   46,   41,   70,   73,   41,   41,   42,   74,   42,
       42,   90,   75,   78,   52,   52,   52,   52,   52,   52,
       53,   79,  101,   76,   77,   41,   41,   41,   80,   41,
       41,   92,   54,   47,   53,   51,   51,   51,   51,   51,
       51,   83,   93,   41,   97,   94,   54,   41,   41,  100,
       41,   95,   54,   52,   52,   52,   52,   52,   52,   91,

       96,   99,   41,  104,   85,   41,   54,   41,   55,   86,
       86,   86,   86,   86,   86,   98,   41,   41,   41,   41,
       85,  106,   87,   87,   85,   88,   88,   88,   88,   88,
       88,   41,   41,   41,   41,   41,   41,  107,  102,  103,
       85,  105,   41,  108,  117,  117,   41,  118,  118,  118,
      118,  118,  118,  121,  109,   41,  110,   41,  119,   41,
      122,  111,   41,   41,   41,   41,  125,  112,  124,  136,
       41,  113,   86,   86,   86,   86,   86,   86,  123,   41,
       41,   41,  116,   85,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   41,  120,   41,   41,

      129,   41,   41,   85,  126,  127,   41,  133,  131,   41,
       41,  135,   41,  130,  128,  137,   41,   41,   41,   41,
      269,  134,   41,  148,  153,  132,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  118,   41,   41,
      138,   41,   41,   41,  152,   41,  150,   41,  139,  144,
      145,  140,  141,   41,  146,  147,  149,   41,  151,   41,
      156,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,  165,   41,  155,  168,
      154,  170,  167,   41,  175,  169,  159,   41,  176,   41,
       41,   41,  160,   41,   41,   41,  183,  157,  158,  171,

      186,  179,  161,   41,  162,  166,  185,   41,  177,  172,
      173,  178,   41,   41,  174,   41,   41,   41,  184,  188,
       41,   41,   41,   41,   41,  180,   41,   41,  187,   41,
       41,   41,  196,  199,   41,  201,  205,   41,   41,   41,
      192,   41,   41,   41,   41,   41,  190,   41,  193,   41,
      189,  200,   41,  194,  191,  202,  212,  213,  206,  195,
      203,  215,   41,  214,  204,  207,   41,   41,   41,  223,
       41,  209,   41,  216,  217,  208,  224,  225,  225,  225,
      226,  226,  228,   41,  220,  218,  219,   41,   41,  223,
       41,   41,   41,  221,  227,   41,  229,  230,   41,   41,

      226,  226,   41,  240,   41,   41,   41,   41,  231,   41,
      244,  233,  232,  239,   41,   41,   41,  241,   41,   41,
       41,   41,  268,   41,  264,  263,  242,  252,  250,  243,
      234,  251,  262,  253,   41,  257,  256,  255,   41,  254,
      245,  258,   41,  259,  249,  248,  260,  247,   41,  238,
      261,  265,  237,  236,  235,   41,  266,   41,  222,   41,
      211,  210,   41,  267,   40,   41,   41,  198,   40,   40,
       40,   45,   45,   45,   45,   45,   45,   45,   48,   48,
      197,   48,   48,   48,   48,   51,   51,   41,   51,   41,
       41,   41,  182,   41,   41,   41,   84,   84,  181,   84,

       84,   84,   84,   89,   89,  246,  246,   41,  246,  246,
      246,  246,   41,   41,   41,  164,  163,   41,   41,   41,
       41,   41,  143,  142,   41,   41,  115,  114,   41,   41,
       41,   41,   41,  270,    3,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270
    } ;

static const flex_int16_t yy_chk[702] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    5,    6,    5,
        5,    6,    7,    8,    7,    7,   11,   11,   11,   11,
       11,   11,   11,   12,   12,   12,   12,   12,   12,   13,
       14,   14,   14,   14,   14,   14,   14,   16,   17,   18,

       19,   13,   14,   21,   18,    8,   20,   20,   22,   17,
       23,   16,   21,   22,   24,   26,   29,   21,   19,   25,
       27,   13,   14,   32,   33,    2,   23,   24,   34,   35,
       25,   27,   17,   27,   28,   39,   24,   13,   26,   38,
       38,   45,   57,   26,   28,  267,   68,   42,   28,   42,
       42,   57,   29,   33,   49,   49,   49,   49,   49,   49,
       50,   34,   68,   32,   32,   59,   67,   58,   35,   64,
       60,   59,   50,   45,   51,   51,   51,   51,   51,   51,
       51,   39,   60,   61,   64,   60,   51,   72,   62,   67,
       66,   61,   50,   52,   52,   52,   52,   52,   52,   58,

       62,   66,   69,   72,   52,   75,   51,   65,   50,   53,
       53,   53,   53,   53,   53,   65,   74,   70,   76,   77,
       53,   74,   54,   54,   52,   54,   54,   54,   54,   54,
       54,   78,   79,   80,   73,   83,  108,   75,   69,   70,
       53,   73,   93,   76,   85,   85,   90,   85,   85,   85,
       85,   85,   85,   93,   77,   94,   78,   96,   90,  266,
       94,   79,   91,  265,   95,   97,   97,   79,   96,  108,
      100,   80,   86,   86,   86,   86,   86,   86,   95,  102,
      107,  109,   83,   86,   87,   87,   87,   87,   87,   87,
       88,   88,   88,   88,   88,   88,   98,   91,  101,   99,

      100,  103,  104,   86,   98,   99,  105,  104,  102,  110,
      111,  107,  112,  101,   99,  109,  120,  113,  123,  130,
      264,  105,  129,  123,  130,  103,  117,  117,  117,  117,
      117,  117,  118,  118,  118,  118,  118,  118,  119,  127,
      110,  121,  122,  124,  129,  131,  127,  128,  111,  119,
      120,  112,  113,  132,  121,  122,  124,  135,  128,  136,
      135,  137,  138,  139,  140,  141,  144,  146,  145,  147,
      149,  154,  152,  150,  155,  156,  144,  157,  132,  147,
      131,  150,  146,  158,  157,  149,  138,  162,  157,  160,
      161,  165,  139,  166,  168,  170,  165,  136,  137,  152,

      170,  161,  140,  171,  141,  145,  168,  173,  158,  154,
      155,  160,  174,  175,  156,  176,  177,  178,  166,  173,
      179,  180,  185,  183,  188,  162,  191,  184,  171,  193,
      192,  187,  180,  183,  194,  185,  192,  195,  196,  203,
      177,  199,  206,  200,  207,  205,  175,  202,  178,  208,
      174,  184,  201,  179,  176,  187,  199,  200,  193,  179,
      188,  202,  209,  201,  191,  194,  213,  214,  215,  211,
      216,  196,  220,  203,  205,  195,  211,  211,  211,  211,
      211,  211,  214,  217,  208,  206,  207,  218,  221,  226,
      230,  227,  228,  209,  213,  229,  215,  216,  231,  232,

      226,  226,  233,  228,  239,  242,  244,  241,  217,  243,
      232,  220,  218,  227,  252,  258,  250,  229,  251,  254,
      259,  261,  263,  260,  257,  256,  230,  242,  239,  231,
      221,  241,  255,  243,  253,  249,  248,  247,  245,  244,
      233,  250,  240,  251,  238,  237,  252,  236,  234,  225,
      254,  258,  224,  223,  222,  219,  259,  212,  210,  204,
      198,  197,  190,  261,  271,  189,  186,  182,  271,  271,
      271,  272,  272,  272,  272,  272,  272,  272,  273,  273,
      181,  273,  273,  273,  273,  274,  274,  172,  274,  275,
      169,  167,  164,  275,  275,  275,  276,  276,  163,  276,

      276,  276,  276,  277,  277,  278,  278,  159,  278,  278,
      278,  278,  153,  151,  148,  143,  142,  134,  133,  126,
      125,  116,  115,  114,  106,   92,   82,   81,   71,   63,
       56,   40,    4,    3,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
/*
 * lexer.l
 *
 * Copyright (C) 1999 Stephen F. White
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program (see the file "COPYING" for details); if 
 * not, write to the Free Software Foundation, Inc., 675 Mass Ave, 
 * Cambridge, MA 02139, USA.
 */
#line 23 "lexer.l"
 /* string parsing rule from gengtype-lex.l/gcc  
     Copyright (C) 2002, 2003 Free Software Foundation, Inc.
 */
#include <stdlib.h>
#include <string.h>
#include "stdafx.h"
#include "swDebugf.h"

#include "Element.h"
#include "EventIn.h"
#include "EventOut.h"
#include "ExposedField.h"
#include "Field.h"
#include "FieldValue.h"
#include "Node.h"
#include "Scene.h"

#include "SFBool.h"
#include "SFNode.h"
#include "MFNode.h"
#include "SFString.h"

#include "parser.h"
#include "y.tab.h"

#define YY_NEVER_INTERACTIVE 1

#ifdef HAVE_LIBZ
# define YY_INPUT(buf, result, max_size) \
            { result = gzread( inputFile , buf, max_size ); }
#else
# define YY_INPUT(buf, result, max_size) \
            { result = fread( buf, 1, max_size, inputFile ); }
#endif

#if defined(__sgi) && !defined(__GNUC__)
#pragma set woff 1110
#endif

long hexint;
bool protoFlag=false;
int protoNested=0;
bool hasX3DFlag=false;
bool hasProfileFlag=false;

void startProto(void)
{
    protoFlag=true;
    if (protoNested > 0)
        scene->setNestedProto();
    scene->addProtoDefinition();       
    if (protoNested > 0)
        scene->setNestedProto();
    protoNested++;
}
void toProto(char* string)
{
    if (protoFlag)
        scene->addToProtoDefinition(string);
}
void stopProto(void)
{
    if (protoNested--==1)
        protoFlag=false;
}
void toComment(char* string)
{
    if (!protoFlag)
        addToCurrentComment(string);
}
#define YY_NO_UNISTD_H 1
#line 778 "<stdout>"
#line 779 "<stdout>"

#define INITIAL 0

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 105 "lexer.l"


#line 994 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 271 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 635 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 107 "lexer.l"
{
                                toProto(yytext); 
                                nodeComment();
                                return WING_BRACKET_ON;
                                }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 113 "lexer.l"
{
                                toProto(yytext); 
                                insideNodeComment();
                                return WING_BRACKET_OFF;
                                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 119 "lexer.l"
{
                                toProto(yytext); 
                                MFComment();
                                return BRACKET_ON;
                                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 125 "lexer.l"
{
                                toProto(yytext); 
                                insideMFComment();
                                return BRACKET_OFF;
                                }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 131 "lexer.l"
{
                                                       toProto(yytext); 
                                                       yylval.sffloat = 
                                                          (float) atof(yytext); 
                                                       return FLOAT_NUM; 
                                                       }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 138 "lexer.l"
{
                                toProto(yytext); 
                                yylval.sffloat = (float) atof(yytext); 
                                return FLOAT_NUM; 
                                }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 144 "lexer.l"
{
                                toProto(yytext); 
                                yylval.int32 = atoi(yytext); 
                                return INT_NUM; 
                                }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 150 "lexer.l"
{ 
                                toProto(yytext); 
                                sscanf(yytext, "%lx", &hexint);
                                yylval.int32 = (int) hexint;
                                return INT_NUM; 
                                }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 157 "lexer.l"
{ toProto(yytext); return SCRIPT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 159 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag && !protoFlag)       
                    return VRML_CUT;
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 167 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return COMPOSED_SHADER; 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 175 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return SHADER_PROGRAM; 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 183 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return PACKAGED_SHADER; 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 191 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return EXPORT; 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 200 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return IMPORT; 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 208 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return AS; 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 216 "lexer.l"
{ toProto(yytext); return DEF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 218 "lexer.l"
{ startProto(); toProto(yytext); return EXTERNPROTO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 220 "lexer.l"
{ toProto(yytext); return FALSE_TOK; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 222 "lexer.l"
{ toProto(yytext); return IS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 224 "lexer.l"
{ toProto(yytext); return NULL_TOK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 226 "lexer.l"
{ startProto(); toProto(yytext); return PROTO; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 228 "lexer.l"
{ toProto(yytext); return ROUTE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 230 "lexer.l"
{ toProto(yytext); return TO; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 232 "lexer.l"
{ toProto(yytext); return TRUE_TOK; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 234 "lexer.l"
{ toProto(yytext); return USE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 236 "lexer.l"
{ toProto(yytext); return EVENT_IN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 238 "lexer.l"
{ toProto(yytext); return EVENT_OUT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 240 "lexer.l"
{ toProto(yytext); return EXPOSED_FIELD; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 242 "lexer.l"
{ toProto(yytext); return FIELD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 244 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return EVENT_IN;
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 252 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return EVENT_OUT;
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 260 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return INPUT_OUTPUT;
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 268 "lexer.l"
{ 
                toProto(yytext); 
                if (hasX3DFlag)       
                    return FIELD;
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 276 "lexer.l"
{ 
                if (hasX3DFlag) {
                    hasProfileFlag = true;
                    return PROFILE;
                } 
                toProto(yytext); 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 286 "lexer.l"
{
                if (hasProfileFlag)
                    return COMPONENT;
                toProto(yytext); 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 294 "lexer.l"
{ 
                if (hasProfileFlag)
                    return META; 
                toProto(yytext); 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 302 "lexer.l"
{ 
                if (hasProfileFlag)
                    return UNIT; 
                toProto(yytext); 
                yylval.id = scene->addSymbol(yytext); 
                return ID;
                }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 310 "lexer.l"
{
                        if (lineno == 1) {
                            lineno++;
                            hasX3DFlag = true;
                            setX3d();
                            scene->setParsedX3dVersion(0);
                            scene->updateSceneMap();
                            return X3D;
                        }
                        toProto(yytext); 
                        toComment(yytext);
                        /* eat up comments */
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 324 "lexer.l"
{
                        if (lineno == 1) {
                            lineno++;
                            hasX3DFlag = true;
                            setX3d();
                            scene->setParsedX3dVersion(-1);
                            scene->updateSceneMap();
                            return X3D;
                        }
                        toProto(yytext); 
                        toComment(yytext);
                        /* eat up comments */
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 338 "lexer.l"
{
                        swDebugf("Warning: about \"%s\": only ",
                                 yytext);
                        swDebugf("ISO/IEC 19775-1:2013");
                        swDebugf(" is currently supported\n"); 
                        if (lineno == 1) {
                            lineno++;
                            hasX3DFlag = true;
                            setX3d();
                            scene->setParsedX3dVersion(-1);
                            scene->updateSceneMap();
                            return X3D;
                        }
                        toProto(yytext); 
                        toComment(yytext);
                        /* eat up comments */
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 356 "lexer.l"
{
                        if (lineno == 1) {
                            scene->errorf("VRML Version 1 not supported\n"); 
                            TheApp->setVrml1Error();
                            return(VRML1);
                        }
                        toProto(yytext); 
                        toComment(yytext);
                        /* eat up comments */
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 368 "lexer.l"
{
                        /* 
                           UTF8 Byte Order Mark (BOM)
                           (used to mark utf8 documents at the beginning) 
                           ignored at the begin of file
                        */
                        if (lineno != 1)
                            return yytext[0];
                        } 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 379 "lexer.l"
{
                                    toProto(yytext); 
                                    yylval.id = scene->addSymbol(yytext); 
                                    return ID_X3D;
                                    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 385 "lexer.l"
{
                                toProto(yytext); 
                                yylval.id = scene->addSymbol(yytext); 
                                return ID;
                                }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 391 "lexer.l"
{
                        toProto(yytext); 
                        for (const char *s = yytext; *s; s++) {
                           if (*s == '\n') lineno++;
                        }
                        yytext[strlen(yytext)-1] = '\0';
                        yylval.id = scene->addSymbol(yytext+1);
                        return STRING;
                        }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 401 "lexer.l"
{
                        toProto(yytext); 
                        toComment(yytext);
                        lineno++; 
                        /* eat up comments */
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 408 "lexer.l"
{
                        toProto(yytext); 
                        toComment(yytext);
                        /* eat up comments */
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 414 "lexer.l"
{
                        toProto(yytext); 
                        /* eat up whitespace and commas */
                        }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 419 "lexer.l"
{ 
                        toProto(yytext); 
                        lineno++; 
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 424 "lexer.l"
{
                        toProto(yytext);  
                        return yytext[0]; 
                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 429 "lexer.l"
ECHO;
	YY_BREAK
#line 1532 "<stdout>"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 271 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 271 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 270);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 429 "lexer.l"


